// Generated by Haxe 4.1.4
(function ($global) { "use strict";
var JsTools = function() {
	window.document.querySelector(".mobileMenu").onclick = function(e) {
		window.document.querySelector(".top-nav").classList.toggle("open");
		e.preventDefault();
	};
};
JsTools.main = function() {
	window.document.addEventListener("DOMContentLoaded",function() {
		new JsTools();
	},false);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
JsTools.main();
})({});
