// Generated by Haxe 3.4.7
(function () { "use strict";
var JsTools = function() {
	JsTools.j(".mobileMenu").click(function(e) {
		JsTools.j(".top-nav").toggleClass("open");
		e.preventDefault();
	});
};
JsTools.main = function() {
	JsTools.j("window").ready(function() {
		new JsTools();
	});
};
JsTools.j = function(q) {
	return $(q);
};
JsTools.main();
})();
