language: haxe

os: linux
dist: trusty

haxe:
  - "3.4.4"
  - "3.4.7"
  - development

install:
    # at some point all npm needs to be in package.json
  - npm install
  - npm install -g uglify-js
  - npm install -g less@2.7
  - npm install -g less-plugin-clean-css@1.5
  - haxelib install all --always
  - haxelib list
    # get hxnodejs from git, haxelib's is outdated
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs

script:
  - haxe build-run-dox.hxml
  - haxe build-samples.hxml
  - haxe heaps.io.hxml

deploy:
  provider: script
  script: haxe deploy.hxml
  on:
    branch: master
    haxe: "3.4.7"
  skip_cleanup: true
