language: haxe

os: linux
dist: trusty

haxe:
  - "4.0.5"
  - development
  
matrix:	
  allow_failures:
    - haxe: development

install:
    # at some point all npm needs to be in package.json
  - npm install

script:
  - npm run css
  - npm run dox:xml
  - npm run dox
  - npm run samples
  - npm run wiki
  - npm run build

deploy:
  provider: script
  script: npm run deploy
  on:
    branch: master
    haxe: "4.0.5"
  skip_cleanup: true
